name: flutter_template
description: "This is a template project structure."

# This line prevents accidental publication to pub.dev.
publish_to: 'none' # Remove if you want to publish to pub.dev

# Application versioning information.
# - version: major.minor.patch+build_number
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons.
  cupertino_icons: ^1.0.6
  
  ## Responsive Design
  flutter_screenutil: ^5.9.3

  ## Dependency Injection
  get_it: ^7.7.0

  ## Network (HTTP requests)
  dio: ^5.4.3+1

  ## State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1

  ## Local Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  ## Map and Geolocation
  # google_maps_flutter: ^2.6.1
  fluster: ^1.2.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  ## Firebase (If required, add the relevant packages)

  ## Utility
  logger: ^2.3.0
  easy_localization: ^3.0.7
  dart_jsonwebtoken: ^2.14.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules for good coding practices.
  flutter_lints: ^3.0.0

flutter:
  # Ensures that Material Icons font is included in your app.
  uses-material-design: true

  # Asset directories for your application.
  assets:
    - assets/translations/
    - assets/animations/
    - assets/images/
    - assets/svgs/

  # Custom fonts can be added in this section if needed.
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700