name: flutter_template
description: "This is a template project structure."

# This line prevents accidental publication to pub.dev.
publish_to: 'none' # Remove if you want to publish to pub.dev

# Application versioning information.
# - version: major.minor.patch+build_number
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons.
  cupertino_icons: ^1.0.6
  
  ## Responsive Design
  flutter_screenutil: ^5.9.3

  ## Dependency Injection
  get_it: ^7.7.0

  ## Network (HTTP requests)
  dio: ^5.4.3+1

  ## State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1

  ## Local Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  ## Map and Geolocation
  # google_maps_flutter: ^2.6.1
  fluster: ^1.2.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  ## Firebase (If required, add the relevant packages)

  ## Utility
  logger: ^2.3.0
  flutter_dotenv: ^5.1.0
  easy_localization: ^3.0.7
  dart_jsonwebtoken: ^2.14.0
  connectivity_plus: ^6.0.5

  ## Uncomment the following lines if you want to use the plugin
  # flutter_svg: ^2.0.9
  # lottie: ^2.7.0
  # dio: ^5.3.3
  # persian_number_utility: ^1.1.3
  # ## Maps
  # flutter_map_marker_cluster: ^1.3.4
  # flutter_typeahead: ^5.0.1
  # dotted_border: ^2.1.0
  # flutter_slidable: ^3.0.1
  # awesome_rating: ^0.0.4
  # uuid: ^4.4.0
  # supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules for good coding practices.
  flutter_lints: ^3.0.0
  # build_runner: ^2.4.6
  # test: ^1.24.3
  # bloc_test: ^9.1.5

flutter:
  # Ensures that Material Icons font is included in your app.
  uses-material-design: true

  # Asset directories for your application.
  assets:
    - assets/translations/
    - assets/animations/
    - assets/images/
    - assets/svgs/
    - .env

  # Custom fonts can be added in this section if needed.
  # example:
  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Thin.ttf
          weight: 100
        - asset: assets/fonts/YekanBakh-Light.ttf
          weight: 300
        - asset: assets/fonts/YekanBakh-Regular.ttf
          weight: 400
        - asset: assets/fonts/YekanBakh-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/YekanBakh-Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakh-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/YekanBakh-Black.ttf
          weight: 900
        # - asset: assets/fonts/YekanBakh-ExtraBlack.ttf
    # Icon
    # - family: IconlyBold
    #   fonts:
    #     - asset: assets/fonts/Iconly-Bold.ttf
    # - family: IconlyOutline
    #   fonts:
    #     - asset: assets/fonts/Iconly-Outline.ttf